-- Create schemas for all source tables with proper types
USE DATABASE TENANT_LAKE;
USE SCHEMA RAW_REAL;

-- grosspayitem with proper TIMESTAMP
CREATE OR REPLACE TABLE GROSSPAYITEM (
    ID NUMBER,
    _TENANT_ID NUMBER,
    JOB_ID NUMBER,
    INVOICE_ID NUMBER,
    TECHNICIAN_ID NUMBER,
    AMOUNT NUMBER(10,2),
    PAIDDURATIONHOURS NUMBER(10,2),
    GROSSPAYITEMTYPE NUMBER,
    BURDENCOSTAMOUNT NUMBER(10,2),
    _RECORD_UPDATED_TS_UTC TIMESTAMP_NTZ,
    ACTIVE NUMBER
);

-- employeegrosspayitem
CREATE OR REPLACE TABLE EMPLOYEEGROSSPAYITEM (
    ID NUMBER,
    _TENANT_ID NUMBER,
    JOB_ID NUMBER,
    INVOICE_ID NUMBER,
    EMPLOYEE_ID NUMBER,
    AMOUNT NUMBER(10,2),
    PAIDDURATIONHOURS NUMBER(10,2),
    GROSSPAYITEMTYPE NUMBER,
    _RECORD_UPDATED_TS_UTC TIMESTAMP_NTZ,
    ACTIVE NUMBER
);

-- payrolladjustment
CREATE OR REPLACE TABLE PAYROLLADJUSTMENT (
    ID NUMBER,
    _TENANT_ID NUMBER,
    INVOICE_ID NUMBER,
    AMOUNT NUMBER(10,2),
    _RECORD_UPDATED_TS_UTC TIMESTAMP_NTZ,
    ACTIVE NUMBER
);

-- employeepayrolladjustment
CREATE OR REPLACE TABLE EMPLOYEEPAYROLLADJUSTMENT (
    ID NUMBER,
    _TENANT_ID NUMBER,
    INVOICE_ID NUMBER,
    EMPLOYEE_ID NUMBER,
    AMOUNT NUMBER(10,2),
    _RECORD_UPDATED_TS_UTC TIMESTAMP_NTZ,
    ACTIVE NUMBER
);

-- customfield with CREATEDON as TIMESTAMP
CREATE OR REPLACE TABLE CUSTOMFIELD (
    ID NUMBER,
    _TENANT_ID NUMBER,
    OWNER_ID NUMBER,
    TYPE_ID NUMBER,
    VALUE VARCHAR,
    CREATEDON TIMESTAMP_NTZ,
    ACTIVE NUMBER
);

-- inventoryreturn with timestamps
CREATE OR REPLACE TABLE INVENTORYRETURN (
    ID NUMBER,
    _TENANT_ID NUMBER,
    INVOICE_ID NUMBER,
    JOB_ID NUMBER,
    MATERIAL_ID NUMBER,
    AMOUNT NUMBER(10,2),
    CREDIT NUMBER(10,2),
    CREATEDON TIMESTAMP_NTZ,
    DATERETURNED DATE,
    ACTIVE NUMBER
);

