-- =============================
-- FACT_INVOICE.sql
-- =============================
create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.FACT_INVOICE (
	INVOICEKEY NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder COMMENT 'Surrogate key',
	INVOICEID NUMBER(38,0) NOT NULL COMMENT 'Natural key from source system',
	JOBID NUMBER(38,0) NOT NULL,
	TENANTID NUMBER(38,0) NOT NULL,
	DATEKEY NUMBER(38,0),
	CUSTOMERKEY NUMBER(38,0),
	LOCATIONKEY NUMBER(38,0),
	BUSINESSUNITKEY NUMBER(38,0),
	JOBTYPEKEY NUMBER(38,0),
	EMPLOYEEKEY NUMBER(38,0),
	JOBKEY NUMBER(38,0),
	INVOICEDON DATE,
	POSTEDDATE DATE,
	INVOICEDATE DATE,
	TRANSACTIONNUMBER VARCHAR(50),
	INVOICESTATUS NUMBER(38,0),
	ISADJUSTMENT BOOLEAN,
	ADJUSTMENTTOINVOICEID NUMBER(38,0),
	TOTALREVENUE NUMBER(20,2),
	INCOMEREVENUE NUMBER(20,2) COMMENT 'Revenue from income GL accounts only (for job revenue calculation)',
	LINEITEMCOUNT NUMBER(38,0),
	EQUIPMENTCOST NUMBER(20,2),
	MATERIALCOST NUMBER(20,2),
	TOTALITEMCOST NUMBER(20,2),
	POUNBILLEDCOST NUMBER(20,2),
	POBILLEDCOST NUMBER(20,2),
	TOTALPOCOST NUMBER(20,2),
	POCOUNT NUMBER(38,0),
	REGULARLABORCOST NUMBER(20,2),
	PIECEWORKCOST NUMBER(20,2),
	LABORBURDENCOST NUMBER(20,2),
	PAYROLLADJUSTMENTCOST NUMBER(20,2),
	TOTALLABORCOST NUMBER(20,2) COMMENT 'Regular + Piecework + Burden + Adjustments (pre-summed from Mat_Invoice_LaborCosts)',
	REGULARLABORHOURS NUMBER(20,2),
	PIECEWORKHOURS NUMBER(20,2),
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	unique (INVOICEID),
	primary key (INVOICEKEY)
)COMMENT='Invoice-level fact with denormalized base measures from Layer 1'
;



-- =============================
-- FACT_INVOICEITEM.sql
-- =============================
create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.FACT_INVOICEITEM (
	INVOICEITEMKEY NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder COMMENT 'Surrogate key',
	INVOICEITEMID NUMBER(38,0) NOT NULL COMMENT 'Natural key from source system',
	INVOICEID NUMBER(38,0) NOT NULL,
	JOBID NUMBER(38,0),
	TENANTID NUMBER(38,0) NOT NULL,
	DATEKEY NUMBER(38,0),
	CUSTOMERKEY NUMBER(38,0),
	LOCATIONKEY NUMBER(38,0),
	BUSINESSUNITKEY NUMBER(38,0),
	JOBTYPEKEY NUMBER(38,0),
	JOBKEY NUMBER(38,0),
	SKUKEY NUMBER(38,0),
	GLACCOUNTKEY NUMBER(38,0),
	POSTEDDATE DATE,
	INVOICEDATE DATE,
	ITEMDESCRIPTION VARCHAR(16777216),
	ITEMSEQUENCE NUMBER(38,0),
	SKUTYPE NUMBER(38,0) COMMENT '1=Material, 2=Equipment, 3=Service (from invoiceitem.skureference_skutype)',
	ITEMREVENUE NUMBER(20,2),
	ITEMQUANTITY NUMBER(20,4),
	ITEMUNITPRICE NUMBER(20,4),
	ITEMCOST NUMBER(20,2),
	ISINCOME BOOLEAN COMMENT 'TRUE if GL Account Type contains \"Income\"',
	ISPOITEM BOOLEAN COMMENT 'TRUE if invoiceitem.procurementsource_purchaseorderitemid is not null',
	POITEMID NUMBER(38,0),
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	unique (INVOICEITEMID),
	primary key (INVOICEITEMKEY)
)COMMENT='Line item-level fact for SKU and product analysis'
;



-- =============================
-- FACT_SERVICEAGREEMENT.sql
-- =============================
create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.FACT_SERVICEAGREEMENT (
	SERVICEAGREEMENTKEY NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder COMMENT 'Surrogate key for this fact',
	SERVICEAGREEMENTID NUMBER(38,0) NOT NULL COMMENT 'Natural key from source system',
	PERIODSTARTDATE DATE NOT NULL COMMENT 'Start date of reporting period (from ETL parameters)',
	PERIODENDDATE DATE NOT NULL COMMENT 'End date of reporting period (from ETL parameters)',
	TENANTID NUMBER(38,0) NOT NULL,
	DATEKEY NUMBER(38,0),
	CUSTOMERKEY NUMBER(38,0),
	LOCATIONKEY NUMBER(38,0),
	BUSINESSUNITKEY NUMBER(38,0),
	EMPLOYEEKEY NUMBER(38,0),
	SERVICEAGREEMENTDIMKEY NUMBER(38,0),
	SANAME VARCHAR(500),
	SATEMPLATETYPE VARCHAR(250),
	SASTARTDATE DATE,
	SAENDDATE DATE,
	SARENEWALYEAR NUMBER(38,0) COMMENT 'Renewal year (1, 2, 3+) based on renewal chain',
	SASTATUS NUMBER(38,0),
	REVENUERECOGNITIONAMOUNT NUMBER(20,2) COMMENT 'Revenue recognized via journal entries in this period',
	LABORCOST NUMBER(20,2) COMMENT 'Direct labor costs from SA visit jobs',
	BURDENCOST NUMBER(20,2) COMMENT 'Labor burden costs from SA visit jobs',
	MATERIALCOST NUMBER(20,2),
	EQUIPMENTCOST NUMBER(20,2),
	SOLDBYEMPLOYEEID NUMBER(38,0) COMMENT 'Employee who sold the SA (for commission calculation)',
	JOBCOMMISSIONPCT NUMBER(10,2),
	SAYEAR1COMMISSIONPCT NUMBER(10,2),
	SAYEAR2COMMISSIONPCT NUMBER(10,2),
	SAYEAR3PLUSCOMMISSIONPCT NUMBER(10,2),
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	unique (SERVICEAGREEMENTID, PERIODSTARTDATE, PERIODENDDATE, TENANTID),
	primary key (SERVICEAGREEMENTKEY)
)COMMENT='Service agreement periodic fact with revenue recognition and visit job costs'
;
