create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.DIM_LOCATION (
	LOCATIONKEY NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder COMMENT 'Surrogate key',
	LOCATIONID NUMBER(38,0) NOT NULL COMMENT 'Natural key from source system',
	TENANTID NUMBER(38,0) NOT NULL,
	LOCATIONNAME VARCHAR(250),
	ISACTIVE BOOLEAN,
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	unique (LOCATIONID, TENANTID),
	primary key (LOCATIONKEY)
)COMMENT='Service location dimension (Type 1 - current state only)'
;
