CREATE OR REPLACE TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.DIM_TENANT (
    TENANTKEY NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER COMMENT 'Surrogate key',
    TENANTID NUMBER(38,0) NOT NULL COMMENT 'Natural key from source system',
    TENANTNAME VARCHAR(250) COMMENT 'Tenant display name',
    TENANTOFFICIALNAME VARCHAR(250) COMMENT 'Tenant official/legal name',
    ISACTIVE BOOLEAN DEFAULT TRUE,
    LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATEDDATETIME TIMESTAMP_NTZ(9),
    UNIQUE (TENANTID),
    PRIMARY KEY (TENANTKEY)
) COMMENT='Tenant dimension (Type 1 - current state only)';

