create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.DIM_BUSINESSUNIT (
	BUSINESSUNITKEY NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder COMMENT 'Surrogate key',
	BUSINESSUNITID NUMBER(38,0) NOT NULL COMMENT 'Natural key from source system',
	TENANTID NUMBER(38,0) NOT NULL,
	BUSINESSUNITNAME VARCHAR(250),
	ISACTIVE BOOLEAN,
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	unique (BUSINESSUNITID, TENANTID),
	primary key (BUSINESSUNITKEY)
)COMMENT='Business unit dimension (Type 1 - current state only)'
;
