create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.DIM_EMPLOYEE (
	EMPLOYEEKEY NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder COMMENT 'Surrogate key',
	EMPLOYEEID NUMBER(38,0) NOT NULL COMMENT 'Natural key from source system',
	TENANTID NUMBER(38,0) NOT NULL,
	EMPLOYEENAME VARCHAR(250),
	EMPLOYEETYPE VARCHAR(50) COMMENT 'Employee, Technician, Salesperson, etc.',
	ISACTIVE BOOLEAN,
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	unique (EMPLOYEEID, TENANTID),
	primary key (EMPLOYEEKEY)
)COMMENT='Employee dimension (Type 1 - current state only)'
;
