create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.ETL_WATERMARK (
	PROCESSNAME VARCHAR(100) NOT NULL,
	LASTRUNSTART TIMESTAMP_NTZ(9),
	LASTRUNEND TIMESTAMP_NTZ(9),
	LASTRUNSTATUS VARCHAR(20),
	LASTSUCCESSFULRUNEND TIMESTAMP_NTZ(9),
	ROWSPROCESSED NUMBER(38,0),
	ERRORMESSAGE VARCHAR(1000),
	CREATEDDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (PROCESSNAME)
);
