create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.MAT_INVOICE_POCOSTS (
	INVOICEID NUMBER(38,0) NOT NULL,
	TENANTID NUMBER(38,0) NOT NULL,
	JOBID NUMBER(38,0),
	POSTEDDATE DATE,
	INVOICEMODIFIEDON TIMESTAMP_NTZ(9),
	LASTPOMODIFIEDON TIMESTAMP_NTZ(9),
	POUNBILLEDCOST NUMBER(20,2) COMMENT 'PO amounts without bills (no inventoryshipment with bill_id)',
	POBILLEDCOST NUMBER(20,2) COMMENT 'PO amounts with bills (sum of inventorybill.total)',
	TOTALPOCOST NUMBER(20,2),
	POCOUNT NUMBER(38,0),
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	primary key (INVOICEID)
)COMMENT='Purchase order costs - refreshed when POs created/billed'
;
