create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.MAT_INVOICE_REVENUE (
	INVOICEID NUMBER(38,0) NOT NULL,
	TENANTID NUMBER(38,0) NOT NULL,
	JOBID NUMBER(38,0),
	INVOICEDATE DATE,
	POSTEDDATE DATE,
	INVOICEMODIFIEDON TIMESTAMP_NTZ(9) COMMENT 'For incremental refresh tracking',
	TRANSACTIONNUMBER VARCHAR(50),
	INVOICESTATUS NUMBER(38,0),
	TOTALREVENUE NUMBER(20,2) COMMENT 'Sum of all invoice items',
	INCOMEREVENUE NUMBER(20,2) COMMENT 'Sum of items with income GL account type',
	LINEITEMCOUNT NUMBER(38,0),
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	primary key (INVOICEID)
)COMMENT='Invoice revenue measures - refreshed when invoices posted/modified'
;