create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.MAT_EMPLOYEE_COMMISSIONRATES (
	EMPLOYEEID NUMBER(38,0) NOT NULL,
	TENANTID NUMBER(38,0) NOT NULL,
	EMPLOYEENAME VARCHAR(250),
	EMPLOYEETYPE VARCHAR(50),
	COMMISSIONTYPE NUMBER(38,0) COMMENT 'From CommissionTypeEmployee custom field',
	JOBCOMMISSIONPCT NUMBER(10,4) COMMENT 'Job Commission% custom field',
	SAYEAR1COMMISSIONPCT NUMBER(10,4) COMMENT 'SA Year 1 Commission% custom field',
	SAYEAR2COMMISSIONPCT NUMBER(10,4) COMMENT 'SA Year 2 Commission% custom field',
	SAYEAR3PLUSCOMMISSIONPCT NUMBER(10,4) COMMENT 'SA Year 3+ Commission% custom field',
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	primary key (EMPLOYEEID)
)COMMENT='Employee commission rates (Type 1 - current state only)'
;
