create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.MAT_INVOICE_MATERIALCOSTS (
	INVOICEID NUMBER(38,0) NOT NULL,
	TENANTID NUMBER(38,0) NOT NULL,
	JOBID NUMBER(38,0),
	POSTEDDATE DATE,
	INVOICEMODIFIEDON TIMESTAMP_NTZ(9),
	EQUIPMENTCOST NUMBER(20,2) COMMENT 'Sum of invoice items from equipment SKUs (non-PO)',
	MATERIALCOST NUMBER(20,2) COMMENT 'Sum of invoice items from material SKUs (non-PO)',
	TOTALITEMCOST NUMBER(20,2) COMMENT 'Equipment + Material',
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	primary key (INVOICEID)
)COMMENT='Equipment and material costs - refreshed when invoices posted/modified'
;
