CREATE OR REPLACE TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.MAT_REPORT_BASELINE (
    RUN_VERSION VARCHAR(50) NOT NULL,
    RUN_DATE DATE NOT NULL,
    RUN_DESCRIPTION VARCHAR(500),
    _TENANTID NUMBER(38,0),
    JOBID NUMBER(38,0),
    JOBREVENUE DECIMAL(20,2),
    LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
) COMMENT='Baseline table for report output comparison';

