create or replace TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.MAT_INVOICE_LABORCOSTS (
	INVOICEID NUMBER(38,0) NOT NULL,
	TENANTID NUMBER(38,0) NOT NULL,
	JOBID NUMBER(38,0),
	POSTEDDATE DATE,
	INVOICEMODIFIEDON TIMESTAMP_NTZ(9),
	LASTLABORMODIFIEDON TIMESTAMP_NTZ(9),
	REGULARLABORCOST NUMBER(20,2) COMMENT 'Regular and overtime labor (grosspayitemtype 2,4)',
	PIECEWORKCOST NUMBER(20,2) COMMENT 'Piecework and performance pay (grosspayitemtype 1,3)',
	LABORBURDENCOST NUMBER(20,2) COMMENT 'Burden calculated from technician.burdenrate × hours',
	PAYROLLADJUSTMENTCOST NUMBER(20,2) COMMENT 'Payroll adjustments from payrolladjustment table',
	TOTALLABORCOST NUMBER(20,2),
	REGULARLABORHOURS NUMBER(20,2),
	PIECEWORKHOURS NUMBER(20,2),
	LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATEDDATETIME TIMESTAMP_NTZ(9),
	primary key (INVOICEID)
)COMMENT='Labor costs - refreshed when gross pay items added/modified'
;
