CREATE OR REPLACE TRANSIENT TABLE ENG_STAGING.BRANDT_REPORT_DM.MAT_METRIC_SUMMARY (
    RUN_VERSION VARCHAR(50) NOT NULL,
    RUN_DATE DATE NOT NULL,
    RUN_DESCRIPTION VARCHAR(500),
    METRIC_NAME VARCHAR(100) NOT NULL,
    METRIC_CATEGORY VARCHAR(50),
    METRIC_VALUE DECIMAL(20,2),
    METRIC_COUNT INTEGER,
    PREVIOUS_RUN_VERSION VARCHAR(50),
    PREVIOUS_METRIC_VALUE DECIMAL(20,2),
    VALUE_DIFFERENCE DECIMAL(20,2),
    VALUE_DIFFERENCE_PCT DECIMAL(10,4),
    LOADDATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RUN_VERSION, RUN_DATE, METRIC_NAME)
) COMMENT='Summary table for tracking metrics across ETL runs';

